### ISSUE TITLE
maint(resources): add a 'final' status check to summarize expected builds

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#14172]
It would be very helpful to have a single status check which summarizes all the expected builds for a given PR. This should be correlated to the trigger-builds infrastructure. This status check should be implemented as a GHA.

Rationale: we cannot specify required status checks in GitHub at this point, because we don't necessarily know which status checks will be required for a given PR.

So, we define a new status check which verifies that all the expected builds for a given PR have passed, and then make that into a required status check for all PRs targeting master,beta,stable-x.y,epic/ branches.

This status check would need to be re-run automatically whenever another status check or commit status completes.

It would be helpful if the status check could give a list of expected builds.

We would use this 'final' status check as the required status check in GH, allowing us to use auto-merge functionality safely.

Relates-to: #14171
Refs:
* https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#check_run
* https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks

theoretical:

```yaml
    on:
      check_suite:
        types: [completed]

    jobs:
      final_check:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Verify all checks passed
            id: verify_checks
            run: |
              # Add script here to check status of all checks
              # and set an output variable (e.g., check_result)
              echo "check_result=success" >> "$GITHUB_OUTPUT"
          - name: Create final check run
            uses: actions/github-script@v7
            with:
              script: |
                const checkResult = process.env.CHECK_RESULT;
                const { owner, repo } = context.repo;
                const { sha } = context.payload.check_suite;
                const conclusion = checkResult === 'success' ? 'success' : 'failure';
                await github.rest.checks.create({
                  owner,
                  repo,
                  head_sha: sha,
                  name: 'Final Status Check',
                  status: 'completed',
                  conclusion: conclusion
                });
```
